/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.move_auto_escola.TelasAulas;

/**
 *
 * @author Dev. Desktop
 */
public class TelaListaAulas extends javax.swing.JPanel {

    /**
     * Creates new form TelaListaAulas
     */
    public TelaListaAulas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollBar1 = new javax.swing.JScrollBar();
        botaoTelaAlunos2 = new javax.swing.JButton();
        botaoTelaAlunos1 = new javax.swing.JButton();
        menu = new javax.swing.JLabel();
        botaoSair = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        menu1 = new javax.swing.JLabel();
        detalhesBtn = new javax.swing.JButton();
        botaoTelaVeiculos = new javax.swing.JButton();

        botaoTelaAlunos2.setBackground(new java.awt.Color(0, 102, 204));
        botaoTelaAlunos2.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        botaoTelaAlunos2.setForeground(new java.awt.Color(255, 255, 255));
        botaoTelaAlunos2.setText("EDITAR");
        botaoTelaAlunos2.setMaximumSize(new java.awt.Dimension(154, 33));
        botaoTelaAlunos2.setMinimumSize(new java.awt.Dimension(154, 33));
        botaoTelaAlunos2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoTelaAlunos2ActionPerformed(evt);
            }
        });

        botaoTelaAlunos1.setBackground(new java.awt.Color(0, 102, 204));
        botaoTelaAlunos1.setFont(new java.awt.Font("Segoe UI Black", 0, 10)); // NOI18N
        botaoTelaAlunos1.setForeground(new java.awt.Color(255, 255, 255));
        botaoTelaAlunos1.setText("Detalhes");
        botaoTelaAlunos1.setMaximumSize(new java.awt.Dimension(154, 33));
        botaoTelaAlunos1.setMinimumSize(new java.awt.Dimension(154, 33));
        botaoTelaAlunos1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoTelaAlunos1ActionPerformed(evt);
            }
        });

        setBackground(new java.awt.Color(51, 51, 51));
        setPreferredSize(new java.awt.Dimension(600, 400));

        menu.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        menu.setForeground(new java.awt.Color(255, 255, 255));
        menu.setText("LISTA AULAS");

        botaoSair.setBackground(new java.awt.Color(0, 0, 102));
        botaoSair.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        botaoSair.setForeground(new java.awt.Color(255, 255, 255));
        botaoSair.setText("Voltar");
        botaoSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoSairActionPerformed(evt);
            }
        });

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Vitor Arthur Andrade Cambui", "Pedro Henrique Silva de Oliveira", "Marcos Wendel" }));

        menu1.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        menu1.setForeground(new java.awt.Color(255, 255, 255));
        menu1.setText("Selecionar Aula:");

        detalhesBtn.setBackground(new java.awt.Color(0, 102, 204));
        detalhesBtn.setFont(new java.awt.Font("Segoe UI Black", 0, 10)); // NOI18N
        detalhesBtn.setForeground(new java.awt.Color(255, 255, 255));
        detalhesBtn.setText("Detalhes");
        detalhesBtn.setMaximumSize(new java.awt.Dimension(154, 33));
        detalhesBtn.setMinimumSize(new java.awt.Dimension(154, 33));
        detalhesBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                detalhesBtnActionPerformed(evt);
            }
        });

        botaoTelaVeiculos.setBackground(new java.awt.Color(0, 102, 204));
        botaoTelaVeiculos.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        botaoTelaVeiculos.setForeground(new java.awt.Color(255, 255, 255));
        botaoTelaVeiculos.setText("Agendar nova aula");
        botaoTelaVeiculos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoTelaVeiculosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(134, 134, 134)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(menu)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(botaoTelaVeiculos, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(detalhesBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(menu1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(botaoSair))
                .addContainerGap(114, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(menu)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(menu1)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botaoTelaVeiculos)
                    .addComponent(detalhesBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 198, Short.MAX_VALUE)
                .addComponent(botaoSair)
                .addGap(29, 29, 29))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void botaoSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoSairActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botaoSairActionPerformed

    private void botaoTelaAlunos2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoTelaAlunos2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botaoTelaAlunos2ActionPerformed

    private void detalhesBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_detalhesBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_detalhesBtnActionPerformed

    private void botaoTelaAlunos1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoTelaAlunos1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botaoTelaAlunos1ActionPerformed

    private void botaoTelaVeiculosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoTelaVeiculosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botaoTelaVeiculosActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoSair;
    private javax.swing.JButton botaoTelaAlunos1;
    private javax.swing.JButton botaoTelaAlunos2;
    private javax.swing.JButton botaoTelaVeiculos;
    private javax.swing.JButton detalhesBtn;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JScrollBar jScrollBar1;
    private javax.swing.JLabel menu;
    private javax.swing.JLabel menu1;
    // End of variables declaration//GEN-END:variables
}
